### ISSUE TITLE
An unhandled exception of type 'System.NullReferenceException' occurred in AdomdClientNetCore.dll: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by jonnyleigh** [bdebaere/Unofficial.Microsoft.AnalysisServices.AdomdClientNetCore#10]
An unhandled exception of type 'System.NullReferenceException' occurred in AdomdClientNetCore.dll: 'Object reference not set to an instance of an object.'
   at Microsoft.AnalysisServices.AdomdClient.StreamInteropHelper.ProcessRequest(XASC comClass, Stream requestStream)
   at Microsoft.AnalysisServices.AdomdClient.IXMLAStream.WriteEndOfMessage()
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.WriteEndOfMessage(Boolean callBaseDirect)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.EndRequest(Boolean useBinaryXml)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CreateSession(ListDictionary properties, Boolean sendNamespaceCompatibility, String sessionToken)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Microsoft.AnalysisServices.AdomdClient.AdomdConnection.IXmlaClientProviderEx.CreateSession(Boolean sendNamespaceCompatibility)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToIXMLA(Boolean createSession)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
   at TestBed.Program.GetDataFromAzureAnalysisService(String query, String databasename) in xxxxx\Program.cs:line 34
   at TestBed.Program.Main(String[] args) in xxxxxxxx\Program.cs:line 14

**Comment by danilovulovic** [comment]
I have the same exception. Does anyone know how to resolve it?

**Comment by jonasrembratttetrapak** [comment]
I haven't delved deep into this but the problem comes from commenting out the assignment of the `XASC` instance in the `IXMLAStream` ctor. I tried restoring it but then I get authentication problemens further downstream.  Seems ADAL gets loded and invoked dynamically, from resource files that aren't included. 

Is this part not implemented or should the client provide the ADAL binaries (as resources)?

**Comment by ShaneK** [comment]
Is there any update on this? I'm also getting this issue

**Comment by ShaneK** [comment]
After more testing, I realized the project I was trying to use this in was actually a .NET Framework 4.6 project (which the official library works for). I switched over to the .NET Core project (they're pretty similar except their frameworks, so I didn't realize the first one wasn't .NET Core), the unofficial library worked without issue.

**Comment by ice1e0** [comment]
The problem is here:
https://github.com/bdebaere/Unofficial.Microsoft.AnalysisServices.AdomdClientNetCore/blob/3faea74bb37a3538af93dd28fd3229aaa397a127/AdomdClientNetCore/Microsoft.AnalysisServices.AdomdClient/IXMLAStream.cs#L23-L28
I removed the commend in line 25 and then it worked.

**Comment by ShaneK** [comment]
Update: I'm getting this issue now on a .NET Core app, but only after I deployed it to an Azure app service. I tried building @ice1e0's branch and including the DLL from it manually and it doesn't seem to have helped.

Not 100% sure this is the same null reference exception, going to try remote debugging today.

Edit: Actually, no. Looks like the issue was caused by some poor configuration. @ice1e0's branch helped resolve my null reference exception

**Comment by dancundy** [comment]
Deployed to Azure and I'm seeing the same issue. Not seeing it when run locally.

**Comment by motoyugota** [comment]
> The problem is here:
> https://github.com/bdebaere/Unofficial.Microsoft.AnalysisServices.AdomdClientNetCore/blob/3faea74bb37a3538af93dd28fd3229aaa397a127/AdomdClientNetCore/Microsoft.AnalysisServices.AdomdClient/IXMLAStream.cs#L23-L28
> 
> 
> I removed the commend in line 25 and then it worked.

PLEASE approve this PR and then release a new version to nuget!

**Comment by rev3ng** [comment]
> > The problem is here:
> > https://github.com/bdebaere/Unofficial.Microsoft.AnalysisServices.AdomdClientNetCore/blob/3faea74bb37a3538af93dd28fd3229aaa397a127/AdomdClientNetCore/Microsoft.AnalysisServices.AdomdClient/IXMLAStream.cs#L23-L28
> > 
> > I removed the commend in line 25 and then it worked.
> 
> PLEASE approve this PR and then release a new version to nuget!

Hi, has anything changed on that?

**Comment by dancundy** [comment]
@rev3ng, Microsoft have finally release an official version. You should probably move over to that if you can, as this repo hasn't been updated in a long time. Not seeing any issues since moving over.

[Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64 ](https://www.nuget.org/packages/Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64/19.9.0.1-Preview?_src=template)

**Comment by rev3ng** [comment]
> @rev3ng, Microsoft have finally release an official version. You should probably move over to that if you can, as this repo hasn't been updated in a long time. Not seeing any issues since moving over.
> 
> [Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64 ](https://www.nuget.org/packages/Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64/19.9.0.1-Preview?_src=template)

I will try a new one. Thanks :)

**Comment by ghost** [comment]
> @rev3ng, Microsoft have finally release an official version. You should probably move over to that if you can, as this repo hasn't been updated in a long time. Not seeing any issues since moving over.
> 
> [Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64 ](https://www.nuget.org/packages/Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64/19.9.0.1-Preview?_src=template)

Note: The Nuget package from Microsoft unfortunately requires .NET Framework X and can therefore not run on non-windows OS. So, there is still a valid reason to keep this repo alive. @bdebaere would love to see PR #17 merged

**Comment by alfsahlman** [comment]
Yes agree with @rev3ng.  I have the same issue and I need this Package since we are running on non win.
